export enum NotificationType {
    ORDER_CREATED = "ORDER_CREATED",
    ORDER_PAID = "ORDER_PAID",
    ORDER_STATUS_CHANGED = "ORDER_STATUS_CHANGED",
  
    DELIVERY_ASSIGNED = "DELIVERY_ASSIGNED",
    DELIVERY_IN_TRANSIT = "DELIVERY_IN_TRANSIT",
    ORDER_DELIVERED = "ORDER_DELIVERED",
  
    LOW_STOCK = "LOW_STOCK",
  
    NEW_ORDER_FOR_SELLER = "NEW_ORDER_FOR_SELLER"
}
  